FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt /app/
COPY *.py /app/
COPY controllers/ /app/controllers/
COPY models/ /app/models/
COPY services/ /app/services/
COPY utils/ /app/utils/

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["flake8"]
CMD ["/app"]