services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fleet-network

  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "5001:5000" 
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--timeout=30", "--", "flask", "run"]
    networks:
      - fleet-network

volumes:
  mysql_data:

networks:
  fleet-network:
    driver: bridge