from .drivers_controller import drivers_blueprint
from .vehicle_controller import vehicle_blueprint
from .routes_controller import rutas_blueprint
from .admin_controller import admin_blueprint
from .dashboard_controller import dashboard_blueprint